database:
  url: "jdbc:sqlserver://100.91.247.70:1433;databaseName=uit;encrypt=true;trustServerCertificate=true;"
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  user: "sa"
  password: "%TTn120897%"

lm:
  api_key: "AIzaSyBlYxw7pMDgeaM5dem43-TBP5mHp33HltY"
  base_url: "https://generativelanguage.googleapis.com/v1beta/models"
  model: "gemini-3-flash-preview:generateContent"
  system_prompt: "system_prompt.txt"